const assets = [
  "./files/a new guest.jpg",
  "./files/AAAAAAH (hq).png",
  "./files/AAAHHH.jpg",
  "./files/alien 2.jpg",
  "./files/alien 3.jpg",
  "./files/alien 4.jpg",
  "./files/alien.jpg",
  "./files/angry cuddled 2.jpg",
  "./files/angry cuddled.jpg",
  "./files/angry sob.jpg",
  "./files/angry.jpg",
  "./files/are you fr.jpg",
  "./files/autumn 2.jpg",
  "./files/autumn.jpg",
  "./files/aww look at him (uncropped).jpg",
  "./files/aww look at him.jpg",
  "./files/baby.jpg",
  "./files/baffled.jpg",
  "./files/baggage.jpg",
  "./files/ball.png",
  "./files/balls.png",
  "./files/beauty 2.jpg",
  "./files/beauty.jpg",
  "./files/big ass nose.jpg",
  "./files/big nose.jpg",
  "./files/bit happy 2.jpg",
  "./files/bit happy.jpg",
  "./files/bite 2.jpg",
  "./files/bite.jpg",
  "./files/blanket (uncropped).jpg",
  "./files/blanket 2.jpg",
  "./files/blanket.png",
  "./files/blankets.jpg",
  "./files/bleh.jpg",
  "./files/blink.jpg",
  "./files/blurry.png",
  "./files/bugs when you lift up the rock.jpg",
  "./files/burger 2.jpg",
  "./files/burger.jpg",
  "./files/camera.jpg",
  "./files/casual.jpg",
  "./files/casually sitting.jpg",
  "./files/chad.jpg",
  "./files/cheese 2.png",
  "./files/cheese.jpg",
  "./files/chiffy.jpg",
  "./files/childrens zone.jpg",
  "./files/chill.jpg",
  "./files/close peek.jpg",
  "./files/close up.png",
  "./files/close-up.jpg",
  "./files/comfy blanket.jpg",
  "./files/confused.jpg",
  "./files/conservative 2.png",
  "./files/conservative.png",
  "./files/contained.png",
  "./files/cool collar.jpg",
  "./files/couch.jpg",
  "./files/creature.jpg",
  "./files/creepy.jpg",
  "./files/creepypasta.jpg",
  "./files/critical hit.jpg",
  "./files/crying.jpg",
  "./files/cuddled 2.jpg",
  "./files/cuddled.jpg",
  "./files/damn thats crazy.jpg",
  "./files/dance.jpg",
  "./files/darkness.jpg",
  "./files/deep sea creature 2.jpg",
  "./files/deep sea creature.jpg",
  "./files/dem paws 2.jpg",
  "./files/dem paws.jpg",
  "./files/demon under your bed.jpg",
  "./files/demon.jpg",
  "./files/derp.jpg",
  "./files/disappointed.png",
  "./files/disapproval.jpg",
  "./files/DISGUSTED.jpg",
  "./files/drowning in plushies.jpg",
  "./files/dry standing.jpg",
  "./files/dumb 2.jpg",
  "./files/dumb sit.png",
  "./files/dumb.png",
  "./files/ear grab.jpg",
  "./files/earless.png",
  "./files/eepy.jpg",
  "./files/egg broke.jpg",
  "./files/egg.jpg",
  "./files/empty stare.png",
  "./files/enraged.jpg",
  "./files/epic selfie 2.jpg",
  "./files/epic selfie.jpg",
  "./files/erm.jpg",
  "./files/erm.png",
  "./files/err.jpg",
  "./files/even uglier.jpg",
  "./files/EVIL CREATURE.png",
  "./files/evil goblin.jpg",
  "./files/EVIL.jpg",
  "./files/ew.jpg",
  "./files/eyebrow raise.jpg",
  "./files/fack u.jpg",
  "./files/far away.jpg",
  "./files/fart 2.jpg",
  "./files/fart.jpg",
  "./files/fatass 2.jpg",
  "./files/fatass.jpg",
  "./files/fear.jpg",
  "./files/fear.png",
  "./files/felinus.jpg",
  "./files/final footage.png",
  "./files/finger.jpg",
  "./files/flat.png",
  "./files/fluffy guy.jpg",
  "./files/fluffy.jpg",
  "./files/four doritos long 2.jpg",
  "./files/four doritos long.jpg",
  "./files/four step stool.jpg",
  "./files/fresh.jpg",
  "./files/from the shadows.png",
  "./files/fuck yuo.jpg",
  "./files/fucked up.png",
  "./files/gamer.jpg",
  "./files/gang.png",
  "./files/garage 2.jpg",
  "./files/garage.jpg",
  "./files/gay.jpg",
  "./files/giant.jpg",
  "./files/giraffe.jpg",
  "./files/gn.jpg",
  "./files/golly jeepers.jpg",
  "./files/goog.png",
  "./files/goog_.png",
  "./files/grab the cat.jpg",
  "./files/grab!!.jpg",
  "./files/green eye.jpg",
  "./files/green eyed 2.png",
  "./files/green eyed.png",
  "./files/grin.jpg",
  "./files/groceries.jpg",
  "./files/grr.jpg",
  "./files/guuuuh.jpg",
  "./files/guweh.jpg",
  "./files/gwah 2.jpg",
  "./files/gwah 3.jpg",
  "./files/gwah.jpg",
  "./files/half view.jpg",
  "./files/hamburger.png",
  "./files/hand lick.jpg",
  "./files/happy face.jpg",
  "./files/he has one braincell.jpg",
  "./files/hearty cuts with real chicken & fish in gravy.jpg",
  "./files/hello there.jpg",
  "./files/hello.jpg",
  "./files/hey.jpg",
  "./files/hide.jpg",
  "./files/hiding.jpg",
  "./files/hii.jpg",
  "./files/holding the bathtub.jpg",
  "./files/horrific 2.jpg",
  "./files/horrific 3.jpg",
  "./files/horrific.jpg",
  "./files/horror.png",
  "./files/huh.jpg",
  "./files/hunter.jpg",
  "./files/i got cash on me.jpg",
  "./files/i will find you.jpg",
  "./files/idiot.jpg",
  "./files/idk.jpg",
  "./files/impatient son.jpg",
  "./files/in bed 2.jpg",
  "./files/in bed.jpg",
  "./files/insane.jpg",
  "./files/it says gullible on the ceiling.jpg",
  "./files/IT_S SNOWING IT_S SNOWING IT_S SNOWING.png",
  "./files/ITS SNOWING (caption).jpg",
  "./files/jawline.jpg",
  "./files/just chillin brah.jpg",
  "./files/just minutes before the sog.jpg",
  "./files/kiss.jpg",
  "./files/lay 2.jpg",
  "./files/lay me down.png",
  "./files/lay.jpg",
  "./files/laying.jpg",
  "./files/lets see if this is true or rubbish.jpg",
  "./files/lick.jpg",
  "./files/like that cat meme from 2012 or smth.jpg",
  "./files/literally DEAD.png",
  "./files/long.jpg",
  "./files/look away.jpg",
  "./files/look.png",
  "./files/looking outside.jpg",
  "./files/looking up.jpg",
  "./files/lovely blanket.jpg",
  "./files/m.jpg",
  "./files/mad 2.jpg",
  "./files/mad.jpg",
  "./files/meow.jpg",
  "./files/mewing.jpg",
  "./files/miau 2.jpg",
  "./files/miau.jpg",
  "./files/mid fart.jpg",
  "./files/mimimi.jpg",
  "./files/moments before disaster.jpg",
  "./files/mrow.jpg",
  "./files/murder 2.jpg",
  "./files/murder.jpg",
  "./files/nap.jpg",
  "./files/new york apartment.jpg",
  "./files/no ears.jpg",
  "./files/nom.jpg",
  "./files/non-deep sea creature.jpg",
  "./files/nose to the right.jpg",
  "./files/nose to the top.jpg",
  "./files/not aaah.png",
  "./files/not so evil anymore.png",
  "./files/okay sure.jpg",
  "./files/one ruffle cheddar long.jpg",
  "./files/outside.jpg",
  "./files/package.jpg",
  "./files/panic.jpg",
  "./files/pants.jpg",
  "./files/pat from the back.jpg",
  "./files/paw 2.jpg",
  "./files/paw licking.jpg",
  "./files/paw.jpg",
  "./files/paws.jpg",
  "./files/peering closer to the enemy.jpg",
  "./files/penis.jpg",
  "./files/pent up.jpg",
  "./files/pet on the back.jpg",
  "./files/pet pet pet.jpg",
  "./files/pet.jpg",
  "./files/pillow.jpg",
  "./files/pinned down.jpg",
  "./files/piss.jpg",
  "./files/plastic cup.png",
  "./files/playground 2.jpg",
  "./files/playground.jpg",
  "./files/plead.jpg",
  "./files/pluh.png",
  "./files/plushie 2.jpg",
  "./files/plushie.jpg",
  "./files/pog.png",
  "./files/polite.jpg",
  "./files/popsicle.jpg",
  "./files/prayers.jpg",
  "./files/prepared.jpg",
  "./files/preparing his attack.jpg",
  "./files/proud stand.jpg",
  "./files/psychopath.jpg",
  "./files/purr.png",
  "./files/pushing away.jpg",
  "./files/quicksand 2.jpg",
  "./files/quicksand.jpg",
  "./files/raaah.jpg",
  "./files/RAAH.jpg",
  "./files/rapidly approaching.jpg",
  "./files/restrained evil.png",
  "./files/rich.jpg",
  "./files/rich.png",
  "./files/rubber ducky.jpg",
  "./files/sad face.png",
  "./files/sad.png",
  "./files/scared.jpg",
  "./files/SCREAM FOR HELP.jpg",
  "./files/scream.jpg",
  "./files/selfie.png",
  "./files/shock.jpg",
  "./files/shocking.jpg",
  "./files/shoes.png",
  "./files/shut up.jpg",
  "./files/side of the road.jpg",
  "./files/side sleep.jpg",
  "./files/sigma.jpg",
  "./files/sit.png",
  "./files/skinwalker pretending to be a cat.jpg",
  "./files/sleeping.jpg",
  "./files/sleepy.jpg",
  "./files/slide to the left.jpg",
  "./files/smirk.jpg",
  "./files/smoke weed every day.jpg",
  "./files/snake.jpg",
  "./files/sneak.jpg",
  "./files/sniff 2.jpg",
  "./files/sniff 3.jpg",
  "./files/sniff.png",
  "./files/snooping around.jpg",
  "./files/snore.jpg",
  "./files/snowed up 2.png",
  "./files/snowed up.jpg",
  "./files/so damn long.jpg",
  "./files/sob.jpg",
  "./files/sobbing.jpg",
  "./files/soft covers.jpg",
  "./files/sog look.png",
  "./files/sog stare.jpg",
  "./files/soggy.jpg",
  "./files/spooky.jpg",
  "./files/stand.jpg",
  "./files/standing out there.jpg",
  "./files/standing.jpg",
  "./files/stare.jpg",
  "./files/stares at you.jpg",
  "./files/staring.png",
  "./files/stealth.jpg",
  "./files/sticking out tongue.jpg",
  "./files/striking a pose.jpg",
  "./files/sun rays.jpg",
  "./files/suspension.jpg",
  "./files/teehee.jpg",
  "./files/terrifying.jpg",
  "./files/THE BEAST HAS AWOKEN.jpg",
  "./files/the crap.jpg",
  "./files/the creature.jpg",
  "./files/the thing.jpg",
  "./files/thing.jpg",
  "./files/thug gangster ass shit 2.jpg",
  "./files/thug gangster ass shit.jpg",
  "./files/tilt.jpg",
  "./files/tired.jpg",
  "./files/tongue.jpg",
  "./files/trampoline fear 2.jpg",
  "./files/trampoline fear.jpg",
  "./files/trampoline trapped.jpg",
  "./files/trampoline.png",
  "./files/trapped.jpg",
  "./files/trauma.jpg",
  "./files/traumatized.jpg",
  "./files/true fear.jpg",
  "./files/trying to sleep.jpg",
  "./files/tub.png",
  "./files/ugly.jpg",
  "./files/UGLY.png",
  "./files/uh um.jpg",
  "./files/um hello.png",
  "./files/unsightly beast.jpg",
  "./files/unsure.jpg",
  "./files/very chill.jpg",
  "./files/very ugly.jpg",
  "./files/waddle.jpg",
  "./files/walking away.jpg",
  "./files/weird sit.jpg",
  "./files/weirdo.jpg",
  "./files/went outside.jpg",
  "./files/wha.jpg",
  "./files/whagt.jpg",
  "./files/what are you talking about.png",
  "./files/what do you want.jpg",
  "./files/what if i just bite you for no reason.jpg",
  "./files/WHAT.jpg",
  "./files/what.png",
  "./files/whats that.jpg",
  "./files/who are you.jpg",
  "./files/whoa.jpg",
  "./files/whuh...png",
  "./files/WHUHH.jpg",
  "./files/why does he look like that.jpg",
  "./files/why the big nose.png",
  "./files/why the wide face.jpg",
  "./files/wide lay.jpg",
  "./files/wink.jpg",
  "./files/wise thinker.jpg",
  "./files/wise.png",
  "./files/woah.jpg",
  "./files/woah.png",
  "./files/womp womp.png",
  "./files/wonderful bench.jpg",
  "./files/wtf did you just say.jpg",
  "./files/wtf.jpg",
  "./files/yay.jpg",
  "./files/yeah okay.jpg",
  "./files/yellow eyed.jpg",
  "./files/you all sicken me.jpg",
  "./files/YOU.jpg",
  "./files/yucky.jpg",
  "./files/yummers.jpg",
  "./files/yummy.jpg",
  "./files/zzz.jpg",
  "./files/zzzzzz.jpg"
];