const assets = [
  "./sogs/a new guest.jpg",
  "./sogs/AAAAAAH (hq).png",
  "./sogs/AAAHHH.jpg",
  "./sogs/alien 2.jpg",
  "./sogs/alien 3.jpg",
  "./sogs/alien 4.jpg",
  "./sogs/alien.jpg",
  "./sogs/angry cuddled 2.jpg",
  "./sogs/angry cuddled.jpg",
  "./sogs/angry sob.jpg",
  "./sogs/angry.jpg",
  "./sogs/are you fr.jpg",
  "./sogs/autumn 2.jpg",
  "./sogs/autumn.jpg",
  "./sogs/aww look at him (uncropped).jpg",
  "./sogs/aww look at him.jpg",
  "./sogs/baby.jpg",
  "./sogs/baffled.jpg",
  "./sogs/baggage.jpg",
  "./sogs/ball.png",
  "./sogs/balls.png",
  "./sogs/beauty 2.jpg",
  "./sogs/beauty.jpg",
  "./sogs/big ass nose.jpg",
  "./sogs/big nose.jpg",
  "./sogs/bit happy 2.jpg",
  "./sogs/bit happy.jpg",
  "./sogs/bite 2.jpg",
  "./sogs/bite.jpg",
  "./sogs/blanket (uncropped).jpg",
  "./sogs/blanket 2.jpg",
  "./sogs/blanket.png",
  "./sogs/blankets.jpg",
  "./sogs/bleh.jpg",
  "./sogs/blink.jpg",
  "./sogs/blurry.png",
  "./sogs/bugs when you lift up the rock.jpg",
  "./sogs/burger 2.jpg",
  "./sogs/burger.jpg",
  "./sogs/camera.jpg",
  "./sogs/casual.jpg",
  "./sogs/casually sitting.jpg",
  "./sogs/chad.jpg",
  "./sogs/cheese 2.png",
  "./sogs/cheese.jpg",
  "./sogs/chiffy.jpg",
  "./sogs/childrens zone.jpg",
  "./sogs/chill.jpg",
  "./sogs/close peek.jpg",
  "./sogs/close up.png",
  "./sogs/close-up.jpg",
  "./sogs/comfy blanket.jpg",
  "./sogs/confused.jpg",
  "./sogs/conservative 2.png",
  "./sogs/conservative.png",
  "./sogs/contained.png",
  "./sogs/cool collar.jpg",
  "./sogs/couch.jpg",
  "./sogs/creature.jpg",
  "./sogs/creepy.jpg",
  "./sogs/creepypasta.jpg",
  "./sogs/critical hit.jpg",
  "./sogs/crying.jpg",
  "./sogs/cuddled 2.jpg",
  "./sogs/cuddled.jpg",
  "./sogs/damn thats crazy.jpg",
  "./sogs/dance.jpg",
  "./sogs/darkness.jpg",
  "./sogs/deep sea creature 2.jpg",
  "./sogs/deep sea creature.jpg",
  "./sogs/dem paws 2.jpg",
  "./sogs/dem paws.jpg",
  "./sogs/demon under your bed.jpg",
  "./sogs/demon.jpg",
  "./sogs/derp.jpg",
  "./sogs/disappointed.png",
  "./sogs/disapproval.jpg",
  "./sogs/DISGUSTED.jpg",
  "./sogs/drowning in plushies.jpg",
  "./sogs/dry standing.jpg",
  "./sogs/dumb 2.jpg",
  "./sogs/dumb sit.png",
  "./sogs/dumb.png",
  "./sogs/ear grab.jpg",
  "./sogs/earless.png",
  "./sogs/eepy.jpg",
  "./sogs/egg broke.jpg",
  "./sogs/egg.jpg",
  "./sogs/empty stare.png",
  "./sogs/enraged.jpg",
  "./sogs/epic selfie 2.jpg",
  "./sogs/epic selfie.jpg",
  "./sogs/erm.jpg",
  "./sogs/erm.png",
  "./sogs/err.jpg",
  "./sogs/even uglier.jpg",
  "./sogs/EVIL CREATURE.png",
  "./sogs/evil goblin.jpg",
  "./sogs/EVIL.jpg",
  "./sogs/ew.jpg",
  "./sogs/eyebrow raise.jpg",
  "./sogs/fack u.jpg",
  "./sogs/far away.jpg",
  "./sogs/fart 2.jpg",
  "./sogs/fart.jpg",
  "./sogs/fatass 2.jpg",
  "./sogs/fatass.jpg",
  "./sogs/fear.jpg",
  "./sogs/fear.png",
  "./sogs/felinus.jpg",
  "./sogs/final footage.png",
  "./sogs/finger.jpg",
  "./sogs/flat.png",
  "./sogs/fluffy guy.jpg",
  "./sogs/fluffy.jpg",
  "./sogs/four doritos long 2.jpg",
  "./sogs/four doritos long.jpg",
  "./sogs/four step stool.jpg",
  "./sogs/fresh.jpg",
  "./sogs/from the shadows.png",
  "./sogs/fuck yuo.jpg",
  "./sogs/fucked up.png",
  "./sogs/gamer.jpg",
  "./sogs/gang.png",
  "./sogs/garage 2.jpg",
  "./sogs/garage.jpg",
  "./sogs/gay.jpg",
  "./sogs/giant.jpg",
  "./sogs/giraffe.jpg",
  "./sogs/gn.jpg",
  "./sogs/golly jeepers.jpg",
  "./sogs/goog.png",
  "./sogs/goog_.png",
  "./sogs/grab the cat.jpg",
  "./sogs/grab!!.jpg",
  "./sogs/green eye.jpg",
  "./sogs/green eyed 2.png",
  "./sogs/green eyed.png",
  "./sogs/grin.jpg",
  "./sogs/groceries.jpg",
  "./sogs/grr.jpg",
  "./sogs/guuuuh.jpg",
  "./sogs/guweh.jpg",
  "./sogs/gwah 2.jpg",
  "./sogs/gwah 3.jpg",
  "./sogs/gwah.jpg",
  "./sogs/half view.jpg",
  "./sogs/hamburger.png",
  "./sogs/hand lick.jpg",
  "./sogs/happy face.jpg",
  "./sogs/he has one braincell.jpg",
  "./sogs/hearty cuts with real chicken & fish in gravy.jpg",
  "./sogs/hello there.jpg",
  "./sogs/hello.jpg",
  "./sogs/hey.jpg",
  "./sogs/hide.jpg",
  "./sogs/hiding.jpg",
  "./sogs/hii.jpg",
  "./sogs/holding the bathtub.jpg",
  "./sogs/horrific 2.jpg",
  "./sogs/horrific 3.jpg",
  "./sogs/horrific.jpg",
  "./sogs/horror.png",
  "./sogs/huh.jpg",
  "./sogs/hunter.jpg",
  "./sogs/i got cash on me.jpg",
  "./sogs/i will find you.jpg",
  "./sogs/idiot.jpg",
  "./sogs/idk.jpg",
  "./sogs/impatient son.jpg",
  "./sogs/in bed 2.jpg",
  "./sogs/in bed.jpg",
  "./sogs/insane.jpg",
  "./sogs/it says gullible on the ceiling.jpg",
  "./sogs/IT_S SNOWING IT_S SNOWING IT_S SNOWING.png",
  "./sogs/ITS SNOWING (caption).jpg",
  "./sogs/jawline.jpg",
  "./sogs/just chillin brah.jpg",
  "./sogs/just minutes before the sog.jpg",
  "./sogs/kiss.jpg",
  "./sogs/lay 2.jpg",
  "./sogs/lay me down.png",
  "./sogs/lay.jpg",
  "./sogs/laying.jpg",
  "./sogs/lets see if this is true or rubbish.jpg",
  "./sogs/lick.jpg",
  "./sogs/like that cat meme from 2012 or smth.jpg",
  "./sogs/literally DEAD.png",
  "./sogs/long.jpg",
  "./sogs/look away.jpg",
  "./sogs/look.png",
  "./sogs/looking outside.jpg",
  "./sogs/looking up.jpg",
  "./sogs/lovely blanket.jpg",
  "./sogs/m.jpg",
  "./sogs/mad 2.jpg",
  "./sogs/mad.jpg",
  "./sogs/meow.jpg",
  "./sogs/mewing.jpg",
  "./sogs/miau 2.jpg",
  "./sogs/miau.jpg",
  "./sogs/mid fart.jpg",
  "./sogs/mimimi.jpg",
  "./sogs/moments before disaster.jpg",
  "./sogs/mrow.jpg",
  "./sogs/murder 2.jpg",
  "./sogs/murder.jpg",
  "./sogs/nap.jpg",
  "./sogs/new york apartment.jpg",
  "./sogs/no ears.jpg",
  "./sogs/nom.jpg",
  "./sogs/non-deep sea creature.jpg",
  "./sogs/nose to the right.jpg",
  "./sogs/nose to the top.jpg",
  "./sogs/not aaah.png",
  "./sogs/not so evil anymore.png",
  "./sogs/okay sure.jpg",
  "./sogs/one ruffle cheddar long.jpg",
  "./sogs/outside.jpg",
  "./sogs/package.jpg",
  "./sogs/panic.jpg",
  "./sogs/pants.jpg",
  "./sogs/pat from the back.jpg",
  "./sogs/paw 2.jpg",
  "./sogs/paw licking.jpg",
  "./sogs/paw.jpg",
  "./sogs/paws.jpg",
  "./sogs/peering closer to the enemy.jpg",
  "./sogs/penis.jpg",
  "./sogs/pent up.jpg",
  "./sogs/pet on the back.jpg",
  "./sogs/pet pet pet.jpg",
  "./sogs/pet.jpg",
  "./sogs/pillow.jpg",
  "./sogs/pinned down.jpg",
  "./sogs/piss.jpg",
  "./sogs/plastic cup.png",
  "./sogs/playground 2.jpg",
  "./sogs/playground.jpg",
  "./sogs/plead.jpg",
  "./sogs/pluh.png",
  "./sogs/plushie 2.jpg",
  "./sogs/plushie.jpg",
  "./sogs/pog.png",
  "./sogs/polite.jpg",
  "./sogs/popsicle.jpg",
  "./sogs/prayers.jpg",
  "./sogs/prepared.jpg",
  "./sogs/preparing his attack.jpg",
  "./sogs/proud stand.jpg",
  "./sogs/psychopath.jpg",
  "./sogs/purr.png",
  "./sogs/pushing away.jpg",
  "./sogs/quicksand 2.jpg",
  "./sogs/quicksand.jpg",
  "./sogs/raaah.jpg",
  "./sogs/RAAH.jpg",
  "./sogs/rapidly approaching.jpg",
  "./sogs/restrained evil.png",
  "./sogs/rich.jpg",
  "./sogs/rich.png",
  "./sogs/rubber ducky.jpg",
  "./sogs/sad face.png",
  "./sogs/sad.png",
  "./sogs/scared.jpg",
  "./sogs/SCREAM FOR HELP.jpg",
  "./sogs/scream.jpg",
  "./sogs/selfie.png",
  "./sogs/shock.jpg",
  "./sogs/shocking.jpg",
  "./sogs/shoes.png",
  "./sogs/shut up.jpg",
  "./sogs/side of the road.jpg",
  "./sogs/side sleep.jpg",
  "./sogs/sigma.jpg",
  "./sogs/sit.png",
  "./sogs/skinwalker pretending to be a cat.jpg",
  "./sogs/sleeping.jpg",
  "./sogs/sleepy.jpg",
  "./sogs/slide to the left.jpg",
  "./sogs/smirk.jpg",
  "./sogs/smoke weed every day.jpg",
  "./sogs/snake.jpg",
  "./sogs/sneak.jpg",
  "./sogs/sniff 2.jpg",
  "./sogs/sniff 3.jpg",
  "./sogs/sniff.png",
  "./sogs/snooping around.jpg",
  "./sogs/snore.jpg",
  "./sogs/snowed up 2.png",
  "./sogs/snowed up.jpg",
  "./sogs/so damn long.jpg",
  "./sogs/sob.jpg",
  "./sogs/sobbing.jpg",
  "./sogs/soft covers.jpg",
  "./sogs/sog look.png",
  "./sogs/sog stare.jpg",
  "./sogs/soggy.jpg",
  "./sogs/spooky.jpg",
  "./sogs/stand.jpg",
  "./sogs/standing out there.jpg",
  "./sogs/standing.jpg",
  "./sogs/stare.jpg",
  "./sogs/stares at you.jpg",
  "./sogs/staring.png",
  "./sogs/stealth.jpg",
  "./sogs/sticking out tongue.jpg",
  "./sogs/striking a pose.jpg",
  "./sogs/sun rays.jpg",
  "./sogs/suspension.jpg",
  "./sogs/teehee.jpg",
  "./sogs/terrifying.jpg",
  "./sogs/THE BEAST HAS AWOKEN.jpg",
  "./sogs/the crap.jpg",
  "./sogs/the creature.jpg",
  "./sogs/the thing.jpg",
  "./sogs/thing.jpg",
  "./sogs/thug gangster ass shit 2.jpg",
  "./sogs/thug gangster ass shit.jpg",
  "./sogs/tilt.jpg",
  "./sogs/tired.jpg",
  "./sogs/tongue.jpg",
  "./sogs/trampoline fear 2.jpg",
  "./sogs/trampoline fear.jpg",
  "./sogs/trampoline trapped.jpg",
  "./sogs/trampoline.png",
  "./sogs/trapped.jpg",
  "./sogs/trauma.jpg",
  "./sogs/traumatized.jpg",
  "./sogs/true fear.jpg",
  "./sogs/trying to sleep.jpg",
  "./sogs/tub.png",
  "./sogs/ugly.jpg",
  "./sogs/UGLY.png",
  "./sogs/uh um.jpg",
  "./sogs/um hello.png",
  "./sogs/unsightly beast.jpg",
  "./sogs/unsure.jpg",
  "./sogs/very chill.jpg",
  "./sogs/very ugly.jpg",
  "./sogs/waddle.jpg",
  "./sogs/walking away.jpg",
  "./sogs/weird sit.jpg",
  "./sogs/weirdo.jpg",
  "./sogs/went outside.jpg",
  "./sogs/wha.jpg",
  "./sogs/whagt.jpg",
  "./sogs/what are you talking about.png",
  "./sogs/what do you want.jpg",
  "./sogs/what if i just bite you for no reason.jpg",
  "./sogs/WHAT.jpg",
  "./sogs/what.png",
  "./sogs/whats that.jpg",
  "./sogs/who are you.jpg",
  "./sogs/whoa.jpg",
  "./sogs/whuh...png",
  "./sogs/WHUHH.jpg",
  "./sogs/why does he look like that.jpg",
  "./sogs/why the big nose.png",
  "./sogs/why the wide face.jpg",
  "./sogs/wide lay.jpg",
  "./sogs/wink.jpg",
  "./sogs/wise thinker.jpg",
  "./sogs/wise.png",
  "./sogs/woah.jpg",
  "./sogs/woah.png",
  "./sogs/womp womp.png",
  "./sogs/wonderful bench.jpg",
  "./sogs/wtf did you just say.jpg",
  "./sogs/wtf.jpg",
  "./sogs/yay.jpg",
  "./sogs/yeah okay.jpg",
  "./sogs/yellow eyed.jpg",
  "./sogs/you all sicken me.jpg",
  "./sogs/YOU.jpg",
  "./sogs/yucky.jpg",
  "./sogs/yummers.jpg",
  "./sogs/yummy.jpg",
  "./sogs/zzz.jpg",
  "./sogs/zzzzzz.jpg"
];